name: 'Clean-up'
description: 'Cleans up redundant builds'
inputs:
  token:
    description: 'GitHub API Token'
    required: true
  workflow_id:
    description: 'Workflow ID'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
